### ISSUE TITLE
Plans on releasing a TypeScript type?

### ISSUE THREAD

**Issue by tomcanac** [cumulio/cumul.io-sdk-nodejs#1]
Hi, everything is in the question:

Are there any plans on doing a TypeScript definition? Would be amazing to have the auto completion features and validation.

Thanks for any information
Tom

**Comment by Kagaherk** [comment]
Hi Tom,

That's definitely on the wishlist for the next version, but we'd like to autogenerate the definitions from our internal API declarations to keep the type defs up-to-date.

Stay tuned!

**Comment by TuanaCelik** [comment]
Hi @tomcanac,

We just released a new version that also includes TypeScript types. Hope that helps.

Best,
Tuana
